name: Windows startup test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  main:
    runs-on: windows-latest
    
    steps:
    - name: Initialize
      uses: actions/checkout@v2
    - name: Set up Python 3.9.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.0
    - name: Run Powershell
      run: |
        powershell
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install poetry
      run: |
        pip install poetry
    - name: Cache poetry virtualenvs
      uses: actions/cache@v2
      id: poetry-cache
      with:
        path: |
          C:\Users\runneradmin\AppData\Local\pypoetry
        key: |
          Yuni-v2.0.0a7
        restore-keys: |
          Yuni-v2.0.0a7
    - name: Install dependencies
      if: |
        steps.poetry-cache.outputs.cache-hit != 'true'
      run: |
        poetry install
    - name: Fetch test environment
      run: |
        $client = new-object System.Net.WebClient
        $client.DownloadFile('https://yuni.lancercmd.cc/statics/actions/.env.prod.example', '.env.prod')
        $client.DownloadFile('https://yuni.lancercmd.cc/statics/actions/nonebot_plugin_rauthman/windows-startup-test.py', '__init__.py')
    - name: Run Python
      run: |
        poetry run python __init__.py
